spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/stores
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB
